[toolchain]
version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
shogun_task = "ELsxP11QYREU4RDadUZS5DXEPPjaqwa4csursWD6aeL6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/gohnny/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
